apiVersion: v1
kind: Namespace
metadata:
  name: web-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-app-deployment
  namespace: web-app
  labels:
    app: static-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web-app
  template:
    metadata:
      labels:
        app: static-web-app
    spec:
      containers:
      - name: web-app
        #  Saying pull from our ECR registry - pipeline overwrites this tag via `kubectl set image` on every deploy
        image: 598892456428.dkr.ecr.us-west-2.amazonaws.com/static-web-app:latest
        ports:
        - containerPort: 80
        # Defines resources constraints for our nodes
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: static-web-app-service
  namespace: web-app
spec:
  type: LoadBalancer
  selector:
    app: static-web-app
  ports:
    - port: 80
      targetPort: 80