name: "Terraform Cloud Automation"

on:
  push:
    branches:
      - master
    paths:
      - 'terraform-aws-eks/**'

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-aws-eks
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - run: terraform init
      - run: terraform plan

  apply:
    name: "Terraform Apply"
    needs: plan
    runs-on: ubuntu-latest
    environment: terraform-apply
    defaults:
      run:
        working-directory: terraform-aws-eks
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - run: terraform init
      - run: terraform apply -auto-approve